### ISSUE TITLE
"icrc7_tokens_of" shows token belonging to twos principals after "icrc37_transfer_from"

### ISSUE THREAD

**Issue by sardariuss** [PanIndustrial-Org/icrc_nft.mo#3]
Hello,

When transferring a token with the _icrc37_transfer_from_ method, the method icrc7_tokens_of shows that the token belongs to both the original owner and the new owner.

Here is a scenario to test it yourself. Alice allows Bob to spend her token. Bob transfer it to Carlos. At the end, you'll see that the method _icrc7_balance_of_ shows that both Alice and Carlos own the token:

[icrc7_bug.sh.txt](https://github.com/user-attachments/files/16550747/icrc7_bug.sh.txt)

**Comment by skilesare** [comment]
Great Catch!

I'll point you to the error and if you have time and want to fix it I'd welcome the pull request.

Most of this will happen in https://github.com/PanIndustrial-Org/icrc7.mo

I have indexes for state.indexes.nft_to_owner and owners_to_nfts.

I have functions for unindexOwner and indexOwner but it looks like I miss updating state.indexes.nft_to_owner.

It also looks like I don't index on set_nft.

Now this doesn't explain the error exactly because it should be unindexing....but I think the wrong from is being referenced.

If you look here: https://github.com/PanIndustrial-Org/icrc37.mo/blob/6b05b99a4f9ff3941baeedc3948fee9fb3418b96/src/lib.mo#L1668C54-L1668C77

I pass caller in to the transfer args and I think that needs to be  transferFromArgs.from.owner so that when finalize transfer gets the previous owner it uses the right principal.  Fortunately the transfer is working properly, it is just the indexing that is off.

Likely we'll also need a quick utility function to reindex everything that can be run from post_upgrade when necessary.

I'll fix all of this when I get a chance, but if you want to try to tackle it first 

set_nfts

**Comment by sardariuss** [comment]
Hey,

Thanks for the quick answer. I'll try to have a look at it soon!
